# List of domains for dynamic specialization
DOMAINS:
  - "Artificial Intelligence"
  - "Computer"
  - "Data Science"
  - "Blockchain Technology"
  - "Supply Chain"
  - "Biotechnology"
  - "Medicine"
  - "Psychology"
  - "Economics"
  - "Finance"
  - "Accounting"
  - "Marketing"
  - "User Research"
  - "Product Manager"
  - "Management"
  - "Human Resources Management"
  - "Education"
  - "Linguistics"
  - "History"
  - "Literature"
  - "Philosophy"
  - "Arts"
  - "Physics"
  - "Chemistry"
  - "Biology"
  - "Astronomy"
  - "Earth Science"
  - "Mathematics"
  - "Statistics"
  - "Agricultural Science"
  - "Journalism and Communication"
  - "Law"
  - "Automobile"
  - "Real Estate"
  - "Manufacturing"
  - "Service Industry"
